#!/bin/bash
echo "total 48
drwxrwxr-x 2 sm sm 4096 Aug 23 11:20 .
drwxrwxr-x 6 sm sm 4096 Aug 23 10:18 ..
-rwxrwxr-x 1 sm sm   36 Aug 23 10:25 0-hello_world
-rwxrwxr-x 1 sm sm   29 Aug 23 10:32 1-confused_smiley
-rwxrwxr-x 1 sm sm   28 Aug 23 10:34 2-hellofile
-rwxrwxr-x 1 sm sm   39 Aug 23 10:38 3-twofiles
-rwxrwxr-x 1 sm sm   33 Aug 23 10:41 4-lastlines
-rwxrwxr-x 1 sm sm   33 Aug 23 10:44 5-firstlines
-rwxrwxr-x 1 sm sm   36 Aug 23 10:55 6-third_line
-rwxrwxr-x 1 sm sm   73 Aug 23 11:09 7-file
-rwxrwxr-x 1 sm sm  638 Aug 23 11:20 8-cwd_state
-rw-rw-r-- 1 sm sm    0 Aug 23 10:46 iacta
-rw-rw-r-- 1 sm sm   78 Aug 23 10:23 README.md
" > ls_cwd_content
